services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: accenture
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080