app:
  datasource:
    bookstore:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/bookstore
      username: accenture
      password: secret

spring:
  jpa:
    hibernate:
      ddl-auto: ''
    show-sql: true
    properties:
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-binding-errors: always
    include-message: always