app:
  datasource:
    bookstore:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/bookstore
      username: accenture
      password: secret

server:
  error:
    include-binding-errors: always
    include-message: always