CREATE TABLE IF NOT EXISTS "authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "books" (
  "isbn" varchar UNIQUE PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "author_id" int NOT NULL
);

ALTER TABLE "books" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id");

INSERT INTO "authors" ("name", "age") VALUES ('Stephen King', 75);
INSERT INTO "authors" ("name", "age") VALUES ('H. G. Wells', 79);

INSERT INTO "books" ("isbn", "title", "author_id") VALUES ('c38b52de-ee2f-42a3-907a-644756878794', 'It', 1);
INSERT INTO "books" (isbn, title, author_id) VALUES ('6f462737-8936-4391-b9b4-aa7bf924ab08',  'The war of the Worlds', 2);